default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: phase2_development

  
test:
  <<: *default
  database: phase2_test


production:
  <<: *default
  database: phase2_production
  username: phase2
  password: <%= ENV['PHASE2_DATABASE_PASSWORD'] %>
